# build app to check for errors, on prs to master
name: Build
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: yarn
      - run: yarn build